---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxy_m.
--- DateTime: 2019/12/17 14:46
---

-- Validate value before writing
-- 写入前验证值
function writeWithValidation(r,name,value)
    if(value >=1 and value <= 10) then
        if not aerospike:exists(r) then
            aerospike:create(r)
        end
        r[name] = value
        aerospike:update(r)
    else
        error("1000:Invalid value")
    end
end

-- Set a particular bin only if record does not already exists.
-- 仅在记录不存在时设置特定的bin
function writeUnique(r,name,value)
    if not aerospike:exists(r) then
        aerospike:create(r)
        r[name] = value
        aerospike:update(r)
    end
end

function readBin(r,name)
    return r[name]
end

function multiplyAndAdd(r,a,b)
    return r['age'] * a + b
end