---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxy_m.
--- DateTime: 2019/12/22 22:17
---

local exports = {}

function exports.hello()
    return "hello"
end

function exports.world()
   return " world!"
end

return exports